///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace COI_Test
{
    public partial class AddDeleteNewSample
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void TestUserCode()
        {
            Report.Log(ReportLevel.Info, "User Code", "Simple code", repo.SampleTypesEditor.SelfInfo);

			// test code
            repo.NewProtocolWizard.SomeContainer2.AdvancedViewButton.Click("1;1");
            repo.SampleTypesEditor.SomeContainer1.AddSampleType.Click("1;1");
            repo.SampleTypesEditor.SomeContainer1.SomeElement.Click("1;1");
            
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Keyboard.Press("test");
            
            repo.SampleTypesEditor.ToggleButton.Click("1;1");
            repo.MyAssaysDesktopExplorer.Unknown.Click("4;5");
            repo.SampleTypesEditor.SomeContainer1.SomeContainer.Click("96;11");
            repo.MyAssaysDesktopExplorer.SomeButton.Click("1;1");
            repo.SampleTypesEditor.SomeContainer1.SomeContainer.Click("141;11");
            repo.SampleTypesEditor.SomeContainer1.ButtonOK.Click("1;1");
            
            repo.NewProtocolWizard.SomeContainer2.SomeCheckBox8.Element.SetAttributeValue("Checked", "True");
            repo.NewProtocolWizard.SomeContainer2.SomeCheckBox8.Element.SetAttributeValue("Checked", "False");
            
            repo.NewProtocolWizard.SomeContainer2.AdvancedViewButton.Click("60;15");
            
            // strange code -- sometimes deleting doesn't work 
            Delay.Duration(100, false);
            repo.SampleTypesEditor.Self.Focus();
            repo.SampleTypesEditor.SomeContainer1.SelfInfo.WaitForExists(5000);
            Delay.Duration(1000, false);
            
            repo.SampleTypesEditor.SomePicture.Click("1;1");
            repo.SampleTypesEditor.SomeContainer1.ButtonOK.Click("1;1");
        }

    }
}