///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace COI_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckEmtpyLayout recording.
    /// </summary>
    [TestModule("44877da9-0b0f-4566-8950-8f4d0b4d2a50", ModuleType.Recording, 1)]
    public partial class CheckEmtpyLayout : ITestModule
    {
        /// <summary>
        /// Holds an instance of the COI_TestRepository repository.
        /// </summary>
        public static COI_TestRepository repo = COI_TestRepository.Instance;

        static CheckEmtpyLayout instance = new CheckEmtpyLayout();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckEmtpyLayout()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckEmtpyLayout Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.EditButton' at 38;8.", repo.NewProtocolWizard.EditButtonInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.EditButton.Click("38;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.Grid.PARTImage' at 14;15.", repo.LayoutEditor.Grid.PARTImageInfo, new RecordItemIndex(1));
            repo.LayoutEditor.Grid.PARTImage.Click("14;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'LayoutEditor.Grid.ElementSaveButton'.", repo.LayoutEditor.Grid.ElementSaveButtonInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.LayoutEditor.Grid.ElementSaveButtonInfo, "Enabled", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.MAINRECT' at 172;186.", repo.LayoutEditor.MAINRECTInfo, new RecordItemIndex(3));
            repo.LayoutEditor.MAINRECT.Click("172;186");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.Grid.PARTImage1' at 13;12.", repo.LayoutEditor.Grid.PARTImage1Info, new RecordItemIndex(4));
            repo.LayoutEditor.Grid.PARTImage1.Click("13;12");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
