///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace COI_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Create recording.
    /// </summary>
    [TestModule("cfb32324-05c9-483a-a325-fe766fc4ccad", ModuleType.Recording, 1)]
    public partial class Create : ITestModule
    {
        /// <summary>
        /// Holds an instance of the COI_TestRepository repository.
        /// </summary>
        public static COI_TestRepository repo = COI_TestRepository.Instance;

        static Create instance = new Create();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Create()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Create Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking Focus() on item 'MyAssaysExplorer'.", repo.MyAssaysExplorer.SelfInfo, new RecordItemIndex(0));
            repo.MyAssaysExplorer.Self.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.SomeContainer.SomeTabPage' at 45;76.", repo.MyAssaysExplorer.SomeContainer.SomeTabPageInfo, new RecordItemIndex(1));
            repo.MyAssaysExplorer.SomeContainer.SomeTabPage.Click("45;76");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.SomeContainer.PARTImage' at 16;13.", repo.MyAssaysExplorer.SomeContainer.PARTImageInfo, new RecordItemIndex(2));
            repo.MyAssaysExplorer.SomeContainer.PARTImage.Click("16;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard'.", repo.NewProtocolWizard.SelfInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.NewProtocolWizard.SelfInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer3.OptionMark' at 1;1.", repo.NewProtocolWizard.SomeContainer3.OptionMarkInfo, new RecordItemIndex(4));
            repo.NewProtocolWizard.SomeContainer3.OptionMark.Click("1;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Checked to 'False' on item 'NewProtocolWizard.SomeContainer3.CreateMultiplexAssay'.", repo.NewProtocolWizard.SomeContainer3.CreateMultiplexAssayInfo, new RecordItemIndex(5));
            repo.NewProtocolWizard.SomeContainer3.CreateMultiplexAssay.Element.SetAttributeValue("Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'NewProtocolWizard.SomeContainer3.CreateMultiplexAssay'.", repo.NewProtocolWizard.SomeContainer3.CreateMultiplexAssayInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer3.CreateMultiplexAssayInfo, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Grid.Next' at 56;14.", repo.NewProtocolWizard.Grid.NextInfo, new RecordItemIndex(7));
            repo.NewProtocolWizard.Grid.Next.Click("56;14");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
