///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace COI_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TryBigOne recording.
    /// </summary>
    [TestModule("e49c9b95-870e-4747-bf2f-12db048e0d83", ModuleType.Recording, 1)]
    public partial class TryBigOne : ITestModule
    {
        /// <summary>
        /// Holds an instance of the COI_TestRepository repository.
        /// </summary>
        public static COI_TestRepository repo = COI_TestRepository.Instance;

        static TryBigOne instance = new TryBigOne();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TryBigOne()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TryBigOne Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.SomeContainer.BigTest' at 37;7.", repo.MyAssaysExplorer.SomeContainer.BigTestInfo, new RecordItemIndex(0));
            repo.MyAssaysExplorer.SomeContainer.BigTest.Click("37;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.SomeContainer.PARTImage1' at 20;16.", repo.MyAssaysExplorer.SomeContainer.PARTImage1Info, new RecordItemIndex(1));
            repo.MyAssaysExplorer.SomeContainer.PARTImage1.Click("20;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(2));
            Delay.Duration(30000, false);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking Focus() on item 'InvalidConfiguration'.", repo.InvalidConfiguration.SelfInfo, new RecordItemIndex(3));
            repo.InvalidConfiguration.Self.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'InvalidConfiguration'.", repo.InvalidConfiguration.SelfInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.InvalidConfiguration.SelfInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InvalidConfiguration.ButtonOK' at 42;11.", repo.InvalidConfiguration.ButtonOKInfo, new RecordItemIndex(5));
            repo.InvalidConfiguration.ButtonOK.Click("42;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.SomeContainer.BigTest' at 42;8.", repo.MyAssaysExplorer.SomeContainer.BigTestInfo, new RecordItemIndex(6));
            repo.MyAssaysExplorer.SomeContainer.BigTest.Click("42;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'MyAssaysExplorer.SomeContainer.BigTest'.", repo.MyAssaysExplorer.SomeContainer.BigTestInfo, new RecordItemIndex(7));
            repo.MyAssaysExplorer.SomeContainer.BigTest.PressKeys("{Delete}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
