///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace COI_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TryTest recording.
    /// </summary>
    [TestModule("ba3a1dbf-8a93-41ce-b276-ebd06809020e", ModuleType.Recording, 1)]
    public partial class TryTest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the COI_TestRepository repository.
        /// </summary>
        public static COI_TestRepository repo = COI_TestRepository.Instance;

        static TryTest instance = new TryTest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TryTest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TryTest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.SomeContainer.Test' at 34;10.", repo.MyAssaysExplorer.SomeContainer.TestInfo, new RecordItemIndex(0));
            repo.MyAssaysExplorer.SomeContainer.Test.Click("34;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.SomeContainer.PARTImage1' at 20;16.", repo.MyAssaysExplorer.SomeContainer.PARTImage1Info, new RecordItemIndex(2));
            repo.MyAssaysExplorer.SomeContainer.PARTImage1.Click("20;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(3));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking Focus() on item 'ProtocolTestMyAssaysAnalysis'.", repo.ProtocolTestMyAssaysAnalysis.SelfInfo, new RecordItemIndex(4));
            repo.ProtocolTestMyAssaysAnalysis.Self.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolTestMyAssaysAnalysis.PARTTabLayoutPanel.SomeTabPage' at 47;96.", repo.ProtocolTestMyAssaysAnalysis.PARTTabLayoutPanel.SomeTabPageInfo, new RecordItemIndex(5));
            repo.ProtocolTestMyAssaysAnalysis.PARTTabLayoutPanel.SomeTabPage.Click("47;96");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolTestMyAssaysAnalysis.PARTTabLayoutPanel.SomeTabPage1' at 85;106.", repo.ProtocolTestMyAssaysAnalysis.PARTTabLayoutPanel.SomeTabPage1Info, new RecordItemIndex(6));
            repo.ProtocolTestMyAssaysAnalysis.PARTTabLayoutPanel.SomeTabPage1.Click("85;106");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolTestMyAssaysAnalysis.PARTTabLayoutPanel.SomeTabPage2' at 56;48.", repo.ProtocolTestMyAssaysAnalysis.PARTTabLayoutPanel.SomeTabPage2Info, new RecordItemIndex(7));
            repo.ProtocolTestMyAssaysAnalysis.PARTTabLayoutPanel.SomeTabPage2.Click("56;48");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolTestMyAssaysAnalysis.SomeContainer1.PARTImage' at 6;17.", repo.ProtocolTestMyAssaysAnalysis.SomeContainer1.PARTImageInfo, new RecordItemIndex(8));
            repo.ProtocolTestMyAssaysAnalysis.SomeContainer1.PARTImage.Click("6;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ProtocolTestMyAssaysAnalysis.PdfViewer'.", repo.ProtocolTestMyAssaysAnalysis.PdfViewerInfo, new RecordItemIndex(9));
            Validate.Attribute(repo.ProtocolTestMyAssaysAnalysis.PdfViewerInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolTestMyAssaysAnalysis.SomeContainer1.Ribbon' at 29;36.", repo.ProtocolTestMyAssaysAnalysis.SomeContainer1.RibbonInfo, new RecordItemIndex(10));
            repo.ProtocolTestMyAssaysAnalysis.SomeContainer1.Ribbon.Click("29;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolTestMyAssaysAnalysis.SomeContainer1.IconImage' at 10;9.", repo.ProtocolTestMyAssaysAnalysis.SomeContainer1.IconImageInfo, new RecordItemIndex(11));
            repo.ProtocolTestMyAssaysAnalysis.SomeContainer1.IconImage.Click("10;9");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
