///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace COI_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The WaitForBigData recording.
    /// </summary>
    [TestModule("9d4c3687-965a-43eb-bc56-bb28001385e6", ModuleType.Recording, 1)]
    public partial class WaitForBigData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the COI_TestRepository repository.
        /// </summary>
        public static COI_TestRepository repo = COI_TestRepository.Instance;

        static WaitForBigData instance = new WaitForBigData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public WaitForBigData()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static WaitForBigData Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Можливо є кращі методи зачекати, поки программа "відвисне"
            Report.Log(ReportLevel.Info, "Wait", "Можливо є кращі методи зачекати, поки программа \"відвисне\"\r\nWaiting 30s for item 'NewProtocolWizard' to exist.", repo.NewProtocolWizard.SelfInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.NewProtocolWizard.SelfInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Grid.Next' at 35;14.", repo.NewProtocolWizard.Grid.NextInfo, new RecordItemIndex(1));
            repo.NewProtocolWizard.Grid.Next.Click("35;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.SomeElement4' at 197;13.", repo.NewProtocolWizard.SomeContainer2.SomeElement4Info, new RecordItemIndex(2));
            repo.NewProtocolWizard.SomeContainer2.SomeElement4.Click("197;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(3));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}B{LShiftKey up}ig{RShiftKey down}T{RShiftKey up}est'.", new RecordItemIndex(4));
            Keyboard.Press("{LShiftKey down}B{LShiftKey up}ig{RShiftKey down}T{RShiftKey up}est");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Grid.Next' at 53;16.", repo.NewProtocolWizard.Grid.NextInfo, new RecordItemIndex(5));
            repo.NewProtocolWizard.Grid.Next.Click("53;16");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
